// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Banco descartável que o Prisma usa para reconstruir o histórico de
    // migrations e comparar com o schema. Sem ele, `migrate diff
    // --from-migrations` não roda — e foi justamente essa comparação que
    // revelou nove tabelas no schema sem nenhuma migration que as criasse.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
